### PR TITLE
Read sf objects as an alternative to read *.shp files in shp_to_inp

### PR DESCRIPTION
**Pull request by DoeringA**
Hello Dominik, 
I have a commit to the shp_to_inp function. As an alternative to read *.shp files one can now also read sf objects. 

Anneke

### CODE REVIEW

**Comment by dleutnant** [comment]
Thanks @DoeringA! The contribution seems quite useful. 
Do you think we could introduce a new function `sf_to_inp` instead of extending the existing one for this? I mean the list of function arguments is quite long. Also, the name of the function is more “shp”-related.

What do you think?

**Comment by DoeringA** [comment]
Yes, you are completely right, the list of function arguments is quite long. First, I thought adding a new function sf_to_inp would make sense. But that function would differ only by a few lines from shp_to_inp. That is why I added it to shp_to_inp. But one could add a function shp_to_inp reading the shp files and store them for example in list_of_sections, and write a function sf_to_inp doing the same with sf objects. Then both functions would call an internal function which adds all other input information to list_of_sections and does the further processing.

I could do that by the end of the week.

**Comment by DoeringA** [comment]
Hello Dominik, I now introduced a new function sf_to_inp and changed the internal structure a bit. Further I wrote a test for the new function.

**Comment by hsonne** [comment]
The changes have been merged to the dev branch instead (PR #80) .

**Pull request closed without merging**
